# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    n = 0

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        MainWindow.setMaximumSize(QtCore.QSize(400, 600))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_text = QtWidgets.QLabel(self.centralwidget)
        self.main_text.setGeometry(QtCore.QRect(0, 0, 400, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.main_text.setFont(font)
        self.main_text.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.main_text.setStyleSheet("background-color: rgb(234, 234, 234);")
        self.main_text.setAlignment(QtCore.Qt.AlignCenter)
        self.main_text.setObjectName("main_text")
        self.output = QtWidgets.QLabel(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(0, 50, 400, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.output.setFont(font)
        self.output.setAlignment(QtCore.Qt.AlignCenter)
        self.output.setObjectName("output")
        self.add_1 = QtWidgets.QPushButton(self.centralwidget)
        self.add_1.setGeometry(QtCore.QRect(100, 150, 200, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.add_1.setFont(font)
        self.add_1.setStyleSheet("background-color: rgb(234, 234, 234);\n"
"border-radius: 20px 20px 20px 20px ;")
        self.add_1.setObjectName("add_1")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_f()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CS:GO Obl1Que Farm"))
        self.main_text.setText(_translate("MainWindow", "CS:GO Obl1Que\'s Farm"))
        self.output.setText(_translate("MainWindow", "0"))
        self.add_1.setText(_translate("MainWindow", "ADD 1"))

    def add_f(self):
        self.add_1.clicked.connect(lambda: self.add_label())

    def add_label(self):
        self.n += 1
        self.output.setText(str(self.n))

import sys

app = QtWidgets.QApplication(sys.argv)
MainWindow = QtWidgets.QMainWindow()
ui = Ui_MainWindow()
ui.setupUi(MainWindow)
MainWindow.show()
sys.exit(app.exec_())